[package]
authors = ["Samray <samrayleung@gmail.com>"]
name = "blog"
version = "0.1.1"

[dependencies]
dotenv = "0.9.0"
error-chain = "0.10.0"
lazy_static = "0.2.8"
r2d2 = "0.7.3"
r2d2-diesel = "0.14.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0.10"
serde_json = "1.0.2"
tera = "0.11"
rust-crypto = "^0.2"
bcrypt = "0.1"
rand = "0.3.16"
ipnetwork = "0.12.7"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"

[dependencies.diesel]
features = ["postgres", "chrono","network-address"]
version = "0.14.0"


diesel_infer_schema = "1.2.0"


[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates", "tera_templates", "json"]
version = "*"
